### ISSUE TITLE
Refactor bai 1

### ISSUE THREAD

**Issue by dao-duc-tung** [MLOpsVN/courses.mlops.vn#18]
- [x] Viết thêm vào page Giới thiệu của bài 1. Giải thích sơ qua về architecture, các flows, các tools sẽ dùng để ng đọc thấy kích thích, và hình dung được có những components chính nào, các flow chính nào

- [x] Review page Phân tích vấn đề của bài 1 mà @dao-duc-tung viết

**Comment by quan-dang** [comment]
https://github.com/MLOpsVN/courses.mlops.vn/pull/20
@dao-duc-tung

**Comment by quan-dang** [comment]
@dao-duc-tung Phân tích vấn đề bài 1 LGTM, merge thôI ạ
