### ISSUE TITLE
Add unique points to ML crash course page

### ISSUE THREAD

**Issue by dao-duc-tung** [MLOpsVN/courses.mlops.vn#22]
Nói về 2 điểm đặc biệt của khoá học
- Là nơi tổng hợp các best practices trong MLOps từ các công ty lớn, và từ nhiều kĩ sư có kinh nghiệm từ khắp thế giới
- Trình bày theo project-oriented, chứ ko phải chỉ nói về lý thuyết, kiến thức thật làm thật

**Comment by quan-dang** [comment]
LGTM
