### ISSUE TITLE
docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', PermissionError(13, 'Permission denied'))

### ISSUE THREAD

**Issue by demdecuong** [MLOpsVN/courses.mlops.vn#68]
**Mô tả bug**
- Tên bug: docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', PermissionError(13, 'Permission denied'))
- Xảy ra ở bài [link tới bài](https://courses.mlops.vn/mlops-crash-course/tong-quan-he-thong/mlops-platform/#start)
- Xảy ra ở bước 
```cd mlops-crash-course-platform && bash run.sh all up ```

**Attachments**
![image](https://user-images.githubusercontent.com/32518096/198869750-e2d0bfb5-de2d-4975-bb80-bfb692c98652.png)

**Specs**
- OS: Ubuntu 22.04
- docker: 20.10.12
- docker-compose: 1.29.2

**May be this help** [stackoverflow](https://stackoverflow.com/questions/71863593/docker-permissionerror-errno-13-permission-denied)
Mình đã fix bằng cách dùng lệnh sau
```bash
sudo chmod 777 /var/run/docker.sock
```

**Comment by dao-duc-tung** [comment]
@demdecuong Hi bạn, mình vừa fix lỗi này xong, bằng cách tạo 1 proxy server để serve docker.sock. Bạn có thể check 2 file dưới đây để xem cách fix:

- https://github.com/MLOpsVN/mlops-crash-course-platform/commit/25602f81f8a0b978ff8661974909b45489f8015d#diff-397808f7b4bd25232961ced706545e03cc82ca831eff98f88fab9948bbdacb5c
- https://github.com/MLOpsVN/mlops-crash-course-code/commit/d3ced8223a2dd0eaa7230a8d5261c3cc35dbbc9c#diff-7fce105cf97a468e86109d1de479169cb4defc5b07a9d63bd029ea7e8028fd72

Mình cũng đã update course content, bạn giúp mình restart lại tất cả các tools và services rồi chạy lại giúp mình nha. Thank bạn
